<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>

    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>

    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>

    <AssemblyName>TrafficMatchBuilder</AssemblyName>
    <RootNamespace>TrafficMatchBuilder</RootNamespace>

    <Version>0.3.0</Version>
    <AssemblyVersion>0.3.0.0</AssemblyVersion>
    <FileVersion>0.3.0.0</FileVersion>
    <InformationalVersion>0.3 Beta</InformationalVersion>

    <Company>TrafficMatch Builder</Company>
    <Authors>Nils</Authors>
    <Product>TrafficMatch Builder</Product>
    <Title>TrafficMatch Builder</Title>
    <Description>Automatic VMR Generator for vPilot and Microsoft Flight Simulator</Description>
    <Copyright>Copyright © 2026 Nils</Copyright>

    <NeutralLanguage>en</NeutralLanguage>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
