using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using TrafficMatchBuilder.Models;

namespace TrafficMatchBuilder.Services;

public sealed class VmrExporter
{
    public void Export(string filePath, IEnumerable<AircraftEntry> entries)
    {
        var usableEntries = entries
            .Where(entry => entry.IsUsable)
            .GroupBy(entry => new { entry.Title, entry.TypeCode, entry.AirlineCode })
            .Select(group => group.First())
            .OrderBy(entry => entry.TypeCode)
            .ThenBy(entry => entry.AirlineCode)
            .ThenBy(entry => entry.Title)
            .ToList();

        var sb = new StringBuilder();

        sb.AppendLine(@"<?xml version=""1.0"" encoding=""utf-8""?>");
        sb.AppendLine(@"<ModelMatchRuleSet>");
        sb.AppendLine(@"  <!-- Generated by TrafficMatch Builder v0.2 Beta -->");

        foreach (var entry in usableEntries)
        {
            var typeCode = Escape(entry.TypeCode);
            var airlineCode = Escape(entry.AirlineCode);
            var modelName = Escape(entry.Title);

            if (!string.IsNullOrWhiteSpace(entry.AirlineCode))
                sb.AppendLine($@"  <ModelMatchRule TypeCode=""{typeCode}"" AirlineCode=""{airlineCode}"" ModelName=""{modelName}"" />");
            else
                sb.AppendLine($@"  <ModelMatchRule TypeCode=""{typeCode}"" ModelName=""{modelName}"" />");
        }

        sb.AppendLine(@"</ModelMatchRuleSet>");

        File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
    }

    private static string Escape(string value) => SecurityElement.Escape(value) ?? "";
}
